### ISSUE TITLE
Updated site doesn't display in Firefox

### ISSUE THREAD

**Issue by marc2k3** [reupen/yuo.be#25]
The homepage displays but if I click on Columns UI, I get this..

![image](https://user-images.githubusercontent.com/62050527/193419342-e4d791e8-dc50-4e36-822d-24391e94e152.png)

FF 105.0.1 / Windows 11 22H2

**Comment by reupen** [comment]
It'll be due to caching – I purged the Cloudflare cache after updating the site, but the browser cache is set to be valid for 4 hours. 

Ctrl-F5 should sort it (or it should resolve itself in a few hours). I need to review the cache headers (for the HTML pages at least), but I was planning to move the site to a static site host anyway.

**Comment by marc2k3** [comment]
I did refresh as per the console message but not a hard refresh. That sorted it. Thanks.
